### PR TITLE
Fix is_approved() to properly check input keys

### LINKED ISSUE #279: FIPS checking imported keys for KDF is wrong
As demonstrated in #278, the checking in `is_approved` of the source key for KDF is wrong as it requires the `CKA_OBJECT_VALIDATION_FLAGS` attribute is present on the object. But in practice, this object is ephemeral and never stored so the check will always fail and consider the base key non-approved for FIPS:

https://github.com/latchset/kryoptic/blob/edc346584d7edd7df88f064d502d1fc6567bdcce/src/fips/indicators.rs#L1268-L1270

Correctly, we should call the `check_key` on the passed object, to check the parameters of the key object are approved.

### PR DESCRIPTION
**Pull request by simo5**
#### Description

Keys may not have the ephemeral validation object on. In that case explicilty heck the key and act accordingly.

Also move some code in helper functions for better readability.

Fixes #279

There are no specific tests because #278 will introduce enough tests to ensure this works correctly

#### Checklist

- [ ] Test suite updated with functionality tests
- [ ] Test suite updated with negative tests
- [x] Rustdoc string were added or updated
- [ ] CHANGELOG and/or other documentation added or updated
- [ ] This is not a code change

#### Reviewer's checklist:

- [ ] Any issues marked for closing are fully addressed
- [ ] There is a test suite reasonably covering new functionality or modifications
- [ ] This feature/change has adequate documentation added
- [ ] A changelog entry is added if the change is significant
- [ ] Code conform to coding style that today cannot yet be enforced via the check style test
- [ ] Commits have short titles and sensible text
- [ ] Doc string are properly updated

### CODE REVIEW

File: src/fips/indicators.rs [hunk 1]
```diff
@@ -1222,6 +1222,30 @@ fn check_key(
...
+    false
+}
+
+/// Adds FIPS validation flag to a key object
+fn add_fips_flag(key: &mut Object) {
+    let flag = match key.get_attr_as_ulong(CKA_OBJECT_VALIDATION_FLAGS) {
+        Ok(f) => f,
+        Err(_) => 0,
+    } | KRF_FIPS;
+    /* Ignores failures, as this is epehermal stuff and the code
```
Comment (Jakuje) [inline src/fips/indicators.rs:1241]:
```suggestion
    /* Ignores failures, as this is ephemeral stuff and the code
```
