### PR TITLE
Fix initialization of info in uninitialized token

### LINKED ISSUE #245: Uninitialized token uses unexpected values for label, manufacturerID and model
Here's what I see when printing information about an unintialized token (using 31ba28c):

```
$ release/sq-cryptoki token list
  - Slot:
    - Description: Kryoptic Slot
    - Manufacturer: Kryoptic Project
    - Hardware version: 0.0
    - Firmware version: 1.1
    - Hardware token: no
    - Removable token: no
    - Token present: yes
  - Token:
    - Label: "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
    - Manufacturer: "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
    - Model: "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
    - Serial number: "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
    - Initialized: no
    - Clock: not present
    - Has a protected authentication path: no
```

It appears that [`Token::get_token_info`](https://github.com/latchset/kryoptic/blob/31ba28c/src/token.rs#L184) is returning "half initialized values."  In particular, the label consists of 16 NUL bytes.   93f54cc5e2a9f0f9d3ff92e439e8faae96c98986 changed the defaults for an initialized token with the commit message:

```
Fix defaults for token info to conform to spec

The spec says all token strings are "space" padded and never zero
terminated.
```

I think it would be good to improve the values returned for an uninitialized token, too.

The spec (version 3.2, draft 13, line 1167) says:

```
	label	application-defined label, assigned during token initialization. MUST be padded with the blank character (‘ ‘). MUST NOT be null-terminated.
```

The spec doesn't seem to say what this should be when the token is uninitialized, but the empty string might be better then a bunch of NULs.

```
	manufacturerID	ID of the device manufacturer. MUST be padded with the blank character (‘ ‘). MUST NOT be null-terminated.
	model	model of the device. MUST be padded with the blank character (‘ ‘). MUST NOT be null-terminated.
```

The specification doesn't seem to say that these fields are initialized when the token is uninitialized, but since that information is available, it seems like they should be set accurately.

### PR DESCRIPTION
**Pull request by simo5**
#### Description

Fixes #245 

#### Checklist

- [ ] Test suite updated with functionality tests
- [ ] Test suite updated with negative tests
- [ ] Rustdoc string were added or updated
- [ ] CHANGELOG and/or other documentation added or updated
- [ ] This is not a code change

#### Reviewer's checklist:

- [ ] Any issues marked for closing are fully addressed
- [ ] There is a test suite reasonably covering new functionality or modifications
- [ ] This feature/change has adequate documentation added
- [ ] A changelog entry is added if the change is significant
- [ ] Code conform to coding style that today cannot yet be enforced via the check style test
- [ ] Commits have short titles and sensible text
- [ ] Doc string are properly updated

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -110,9 +110,9 @@ macro_rules! cast_or_ret {
     }};
 }
 
-/// Thread-local instance of the Cryptographically Secure Pseudo-Random Number
-/// Generator (CSPRNG). This is used to avoid contention and locking between
-/// different threads.
+/* Thread-local instance of the Cryptographically Secure Pseudo-Random Number
+ * Generator (CSPRNG). This is used to avoid contention and locking between
+ * different threads. */
```
Comment (Jakuje) [inline src/lib.rs:115]: I would probably add a note here with explanation why this is not a doc string, otherwise next one going through the missing docs string in the source will try to convert it back ;)

Comment (simo5) [reply src/lib.rs:115]: I am not sure we'll go thorough that again, I think it is fine as is, it is easy to change even if we regress, it is only a cosmetic annoyance.
If we care really to no "regress" I would rather add a CI test that fails on these kind of warnings

**Comment by simo5** [comment]
Thanks for the review!
