### PR TITLE
Fix incorrect error returned on un-initialized operations

### LINKED ISSUE #191: Multi-part functions return `CKR_GENERAL_ERROR` when used in a non-initialized state
Hello Kryoptic team!

Currently, calls to multi-part functions (such as `C_DigestUpdate`/`Final` and `C_EncryptUpdate`/`Final`) return the error `CKR_GENERAL_ERROR` when they are called without first calling the corresponding initialization function. However, I believe the more appropriate error here is `CKR_OPERATION_NOT_INITIALIZED`.

As described in the spec, this error applies when "there is no active operation of an appropriate type in the specified session. For example, an application cannot call **C_Encrypt** in a session without having called **C_EncryptInit** first to activate an encryption operation."

### PR DESCRIPTION
**Pull request by simo5**
#### Description

Fixes #191 
#### Checklist

- [x] Test suite updated with functionality tests
- [x] Test suite updated with negative tests
- ~[ ] Documentation was updated~
- ~[ ] This is not a code change~

#### Reviewer's checklist:

- [x] Any issues marked for closing are fully addressed
- [x] There is a test suite reasonably covering new functionality or modifications
- [ ] This feature/change has adequate documentation added
- [ ] A changelog entry is added if the change is significant
- [x] Code conform to coding style that today cannot yet be enforced via the check style test
- [x] Commits have short titles and sensible text

### CODE REVIEW

File: src/tests/session.rs [hunk 1]
```diff
@@ -156,6 +156,19 @@ fn test_operations() {
         ulParameterLen: 0,
     };
 
+    /* Ensure that trying to call an operation w/o initialization returns
+     * the propoer error
```
Comment (Jakuje) [inline src/tests/session.rs:160]:
```suggestion
     * the proper error
```

**Review by Jakuje — APPROVED** [review]
just typo and formatting. Otherwise lgtm
