### PR TITLE
Return error on subsequent C_Initialize calls

### LINKED ISSUE #375: Subsequent calls to C_Initialize do not return CKR_CRYPTOKI_ALREADY_INITIALIZED
Hello and thanks a lot for this useful library 👋 We use it a lot in `rust-cryptoki`!

Refactoring code, I noticed that the following test started to fail. We are calling `C_Initialize` twice in a row and check that the second one returns `CKR_CRYPTOKI_ALREADY_INITIALIZED`. It does not return an error when testing with `kryoptic`, as in panics with `"Initializing twice should not have been allowed"`.

```rust
fn is_initialized_test() -> TestResult {
    use cryptoki::context::CInitializeArgs;

    let pkcs11 = get_pkcs11();

    // initialize the library
    pkcs11.initialize(CInitializeArgs::OsThreads)?;

    match pkcs11.initialize(CInitializeArgs::OsThreads) {
        Err(Error::Pkcs11(RvError::CryptokiAlreadyInitialized, Function::Initialize)) => (), // expected
        Err(e) => panic!("Got unexpected error when initializing: {e}"),
        Ok(()) => panic!("Initializing twice should not have been allowed"),
    }

    pkcs11.finalize()?;

    Ok(())
}
```

### PR DESCRIPTION
**Pull request by simo5**
#### Description

The PKCS#11 specification requires that C_Initialize return CKR_CRYPTOKI_ALREADY_INITIALIZED if it is called more than once. This change implements this behavior by checking the initialization state at the start of the function.

This also resolves an issue where parallel test execution via `cargo test` would fail, as multiple tests would attempt to initialize the same global state. The test assertions have been updated to accept either CKR_OK or CKR_CRYPTOKI_ALREADY_INITIALIZED.

Fixes #375 

#### Checklist

- [x] Test suite updated with functionality tests
- [ ] Test suite updated with negative tests
- [ ] Rustdoc string were added or updated
- [ ] CHANGELOG and/or other documentation added or updated
- [ ] This is not a code change

#### Reviewer's checklist:

- [ ] Any issues marked for closing are fully addressed
- [ ] There is a test suite reasonably covering new functionality or modifications
- [ ] This feature/change has adequate documentation added
- [ ] A changelog entry is added if the change is significant
- [ ] Code conform to coding style that today cannot yet be enforced via the check style test
- [ ] Commits have short titles and sensible text
- [ ] Doc string are properly updated

### CODE REVIEW

File: src/tests/init.rs [hunk 1]
```diff
@@ -16,7 +16,7 @@ fn test_init_token() {
     let mut args = TestToken::make_init_args(Some(testtokn.make_init_string()));
     let args_ptr = &mut args as *mut CK_C_INITIALIZE_ARGS;
     let mut ret = fn_initialize(args_ptr as *mut std::ffi::c_void);
-    assert_eq!(ret, CKR_OK);
+    assert!(ret == CKR_OK || ret == CKR_CRYPTOKI_ALREADY_INITIALIZED);
```
Comment (Jakuje) [inline src/tests/init.rs]: wonder if something like this would help the reporting and would be more "rust-way":
```suggestion
    match ret {
        CK_OK | CKR_CRYPTOKI_ALREADY_INITIALIZED => (), // OK
        _ => panic!("C_Initialize returned unexpected value {ret}")
    }
```

**Comment by simo5** [comment]
> > > Should we have an explicit test to verify the C_Initialize actually return the `CKR_CRYPTOKI_ALREADY_INITIALIZED` when called repetitively in one function?
> > 
> > 
> > It would have to be an external test, because we always get CKR_CRYPTOKI_ALREADY_INITIALIZED except for the first test, but we do not know which one is the first because they all run in parallel.
> 
> But if we call it twice in ONE test, it should do, shouldn't?

No. All tests run in the same binary, the very first test that is run (whichever it is) will get CKR_OK, *all* other tests will only ever get CKR_CRYPTOKI_ALREADY_INITIALIZED now.
